package dev.wintergreen.engine.render.gl.enums

import org.lwjgl.opengl.GL11C
import org.lwjgl.opengl.GL14C

enum class BlendFactor(private val value: Int) : GLEnum {
    ZERO(GL11C.GL_ZERO),
    ONE(GL11C.GL_ONE),
    SRC_COLOR(GL11C.GL_SRC_COLOR),
    ONE_MINUS_SRC_COLOR(GL11C.GL_ONE_MINUS_SRC_COLOR),
    DST_COLOR(GL11C.GL_DST_COLOR),
    ONE_MINUS_DST_COLOR(GL11C.GL_ONE_MINUS_DST_COLOR),
    SRC_ALPHA(GL11C.GL_SRC_ALPHA),
    ONE_MINUS_SRC_ALPHA(GL11C.GL_ONE_MINUS_SRC_ALPHA),
    DST_ALPHA(GL11C.GL_DST_ALPHA),
    ONE_MINUS_DST_ALPHA(GL11C.GL_ONE_MINUS_DST_ALPHA),
    CONSTANT_COLOR(GL14C.GL_CONSTANT_COLOR),
    ONE_MINUS_CONSTANT_COLOR(GL14C.GL_ONE_MINUS_CONSTANT_COLOR),
    CONSTANT_ALPHA(GL14C.GL_CONSTANT_ALPHA),
    ONE_MINUS_CONSTANT_ALPHA(GL14C.GL_ONE_MINUS_CONSTANT_ALPHA);

    override fun value(): Int {
        return value
    }

}